# Generated by Django 3.2.7 on 2021-10-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_complex_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecificProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.size')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='specific',
            field=models.ManyToManyField(related_name='product_with_size', through='base.SpecificProduct', to='base.Size'),
        ),
    ]
