# Generated by Django 3.2.9 on 2021-12-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_prac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nested_1', models.CharField(max_length=32)),
                ('prac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_prac.practice')),
            ],
        ),
    ]
